### PR TITLE
Testing, Routing and Fixes

### PR DESCRIPTION
**Pull request by matenia**
- Fixed Tests + Added test for click_through
- Fixed Generator (now uses templates and invokes the migration-install)
- Updated Readme
- Adjusted routes
- Fixed indenting

output from tests:

$ bundle exec rake test
Run options: 
# Running tests:

....................

Finished tests in 1.569714s, 12.7412 tests/s, 18.4747 assertions/s.

20 tests, 29 assertions, 0 failures, 0 errors, 0 skips

### CODE REVIEW

**Comment by matenia** [comment]
Thanks. Would it be possible for you to open up the wiki on this project?

**Comment by zhinanhu** [comment]
Dear Matenia,

We opened up the wiki.

Thanks!

--Tyler

------------------ 原始邮件 ------------------
发件人: "Matenia Rossides"notifications@github.com;
发送时间: 2012年8月15日(星期三) 下午5:10
收件人: "kudelabs/ad_man"ad_man@noreply.github.com; 

主题: Re: [ad_man] Testing, Routing and Fixes (#2)

Thanks. Would it be possible for you to open up the wiki on this project?

```
           —
           Reply to this email directly or view it on GitHub.
```

**Comment by matenia** [comment]
Thanks, however that was "Issues", I was after the wiki.

**Comment by leondu** [comment]
@matenia,  it's live now.

**Comment by matenia** [comment]
Thanks :D

**Pull request merged**
